# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/vikramsingh/Desktop/coding/vikraft

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/vikramsingh/Desktop/coding/vikraft

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vikramsingh/Desktop/coding/vikraft/CMakeFiles /Users/vikramsingh/Desktop/coding/vikraft//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vikramsingh/Desktop/coding/vikraft/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named proto_lib

# Build rule for target.
proto_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 proto_lib
.PHONY : proto_lib

# fast build rule for target.
proto_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto_lib.dir/build.make CMakeFiles/proto_lib.dir/build
.PHONY : proto_lib/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

proto/service.grpc.pb.o: proto/service.grpc.pb.cc.o
.PHONY : proto/service.grpc.pb.o

# target to build an object file
proto/service.grpc.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto_lib.dir/build.make CMakeFiles/proto_lib.dir/proto/service.grpc.pb.cc.o
.PHONY : proto/service.grpc.pb.cc.o

proto/service.grpc.pb.i: proto/service.grpc.pb.cc.i
.PHONY : proto/service.grpc.pb.i

# target to preprocess a source file
proto/service.grpc.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto_lib.dir/build.make CMakeFiles/proto_lib.dir/proto/service.grpc.pb.cc.i
.PHONY : proto/service.grpc.pb.cc.i

proto/service.grpc.pb.s: proto/service.grpc.pb.cc.s
.PHONY : proto/service.grpc.pb.s

# target to generate assembly for a file
proto/service.grpc.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto_lib.dir/build.make CMakeFiles/proto_lib.dir/proto/service.grpc.pb.cc.s
.PHONY : proto/service.grpc.pb.cc.s

proto/service.pb.o: proto/service.pb.cc.o
.PHONY : proto/service.pb.o

# target to build an object file
proto/service.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto_lib.dir/build.make CMakeFiles/proto_lib.dir/proto/service.pb.cc.o
.PHONY : proto/service.pb.cc.o

proto/service.pb.i: proto/service.pb.cc.i
.PHONY : proto/service.pb.i

# target to preprocess a source file
proto/service.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto_lib.dir/build.make CMakeFiles/proto_lib.dir/proto/service.pb.cc.i
.PHONY : proto/service.pb.cc.i

proto/service.pb.s: proto/service.pb.cc.s
.PHONY : proto/service.pb.s

# target to generate assembly for a file
proto/service.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto_lib.dir/build.make CMakeFiles/proto_lib.dir/proto/service.pb.cc.s
.PHONY : proto/service.pb.cc.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/raft_network.o: src/raft_network.cpp.o
.PHONY : src/raft_network.o

# target to build an object file
src/raft_network.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/raft_network.cpp.o
.PHONY : src/raft_network.cpp.o

src/raft_network.i: src/raft_network.cpp.i
.PHONY : src/raft_network.i

# target to preprocess a source file
src/raft_network.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/raft_network.cpp.i
.PHONY : src/raft_network.cpp.i

src/raft_network.s: src/raft_network.cpp.s
.PHONY : src/raft_network.s

# target to generate assembly for a file
src/raft_network.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/raft_network.cpp.s
.PHONY : src/raft_network.cpp.s

src/raft_node.o: src/raft_node.cpp.o
.PHONY : src/raft_node.o

# target to build an object file
src/raft_node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/raft_node.cpp.o
.PHONY : src/raft_node.cpp.o

src/raft_node.i: src/raft_node.cpp.i
.PHONY : src/raft_node.i

# target to preprocess a source file
src/raft_node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/raft_node.cpp.i
.PHONY : src/raft_node.cpp.i

src/raft_node.s: src/raft_node.cpp.s
.PHONY : src/raft_node.s

# target to generate assembly for a file
src/raft_node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/raft_node.cpp.s
.PHONY : src/raft_node.cpp.s

src/timer.o: src/timer.cpp.o
.PHONY : src/timer.o

# target to build an object file
src/timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/timer.cpp.o
.PHONY : src/timer.cpp.o

src/timer.i: src/timer.cpp.i
.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/timer.cpp.i
.PHONY : src/timer.cpp.i

src/timer.s: src/timer.cpp.s
.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/timer.cpp.s
.PHONY : src/timer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... proto_lib"
	@echo "... server"
	@echo "... proto/service.grpc.pb.o"
	@echo "... proto/service.grpc.pb.i"
	@echo "... proto/service.grpc.pb.s"
	@echo "... proto/service.pb.o"
	@echo "... proto/service.pb.i"
	@echo "... proto/service.pb.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/raft_network.o"
	@echo "... src/raft_network.i"
	@echo "... src/raft_network.s"
	@echo "... src/raft_node.o"
	@echo "... src/raft_node.i"
	@echo "... src/raft_node.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

